### ISSUE TITLE
Naming issue with PIP

### ISSUE THREAD

**Issue by LOMS** [yceruto/django-ajax#15]
Just discovered, pip freeze gives me "django-ajax==2.2.12", but attempt to install django-ajax==2.2.12 causes an error, because it registered like "djangoajax"

**Comment by yceruto** [comment]
@LOMS django-ajax is another package, use pip install djangoajax

**Comment by LOMS** [comment]
You didn't understand me right. Try "pip freeze" after "pip install djangoajax".
