### ISSUE TITLE
multiple ajaxGet arguments in .keyup don't work.

### ISSUE THREAD

**Issue by pythad** [yceruto/django-ajax#21]
$("#search").keyup(function() {
		delay(function() {
			var data = {
				query: $("#search").val()
			}
			if (GLOBAL_VARS.link_id) {
				data.pk = GLOBAL_VARS.link_id;
			}
			ajaxGet(GLOBAL_VARS.distributorsSearchDistUrl, data, function(content) {
				$('#distributors').html(content);
				set_favorite();
			});
		}, 500);
	});

don't want to work. First query works normal, with `V` I got:
`http://127.0.0.1:8000/distributors/search_dist?query=V&pk=64`
second query with `VV` returned me:
`http://127.0.0.1:8000/distributors/search_dist?query=V` without `pk`.
The same function but with $.get() works perfect, so I believe the problem is on your side.

**Comment by yceruto** [comment]
@pythad it's possible that the problem is on my side, but to fix it, I need the error message or something that tells me I can be wrong. Please send me some information about the error and will be corrected at the time. Thank you for your notice.
