### ISSUE TITLE
@ajax decorator returns blank page

### ISSUE THREAD

**Issue by mrigdon** [yceruto/django-ajax#29]
I tried the example 

```python
from django_ajax.decorators import ajax

@ajax
def test_ajax(request):
    return render(request, 'base.html')
```

and I get nothing but a blank screen. What else am I supposed to do to make it work?

**Comment by yceruto** [comment]
@mrigdon could you explain a little more about the environment in which the error occurs. version of python / django, etc.

**Comment by mrigdon** [comment]
Django v 1.8.6 and Python 2.7.6. Perhaps you could give a more robust example of how to use the decorator. Is the decorator supposed to simply render the passed template without refreshing the page?

**Comment by yceruto** [comment]
@mrigdon @ajax decorator work using ajax request only, perhaps you're referring directly through the browser? on the browser console the following error should appear: `Failed to load resource: the server responded with a status of 400 (BAD REQUEST)` see more http://yceruto.github.io/django-ajax/
