### ISSUE TITLE
Input (Form) Validation

### ISSUE THREAD

**Issue by timolson** [yceruto/django-ajax#30]
I don't understand how django-ajax would work with Django Forms to provide input validation.  Seems like processing raw JSON input in your views would be a major security hole.  Do you have a recommendation for how to validate requests?

**Comment by yceruto** [comment]
Hi @timolson, sorry for the delay, I'm completely busy. I suggest you to use some js validation plugins before send your forms, like https://github.com/jzaefferer/jquery-validation for instance. It's not the goal of this library.

Closing as "wontfix"

**Comment by timolson** [comment]
Note to anyone who sees this issue: client side validation is utterly insufficient for security purposes since it is easily fooled. Please use server side validation for security and client side only for user convenience.
