### ISSUE TITLE
Add support for datetime.date type

### ISSUE THREAD

**Issue by pedrodevoto** [yceruto/django-ajax#35]
Whenever there is a datetime.date type object in the response, it raises the following exeption:

```
TypeError: datetime.date(2016, 06, 22) is not JSON serializable
```

**Comment by yceruto** [comment]
Hi @pedrodevoto, sorry for the delay, I'm completely busy. I'll check it later, thanks!

**Comment by jdruiter** [comment]
Is it solved?

**Comment by yceruto** [comment]
Fixed in https://github.com/yceruto/django-ajax/commit/ddc7882ba183e81b015ef02b476eb244e9ac30ce

New releases `3.0.1` and `2.4.1` are available with this fix!
