### ISSUE TITLE
ajax request doesn't pick up csrf cookie value from previous ajax requests

### ISSUE THREAD

**Issue by AndreCimander** [yceruto/django-ajax#38]
We just stumbled over a problem when using ajax modals on our site for new site visitors. The modal request returns a new csrf cookie, but the csrftoken var in the jquery.ajax.idb.min.js on line 23 is only read once.

We fixed the issue by inlining the getCookie('csrftoken'); into the beforeSend function on line 53 :)

**Comment by yceruto** [comment]
Thanks for reporting this issue, I'll solve this ASAP.

**Comment by yceruto** [comment]
Fixed and released in v2.3.7, thanks!
