### ISSUE TITLE
MiddleWare Error

### ISSUE THREAD

**Issue by fmatray** [yceruto/django-ajax#41]
Hello,
I get this error when I load the middleware with django 1.11:
```
 mw_instance = middleware(handler)
TypeError: object() takes no parameters
```

I added this to correct the message
```
class AJAXMiddleware(object):
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.get_response(request)
        return response


```

**Comment by yceruto** [comment]
Thanks for reporting this bug, I'll take a look ASAP!

**Comment by yceruto** [comment]
Sorry, I can't repoduce the issue, see passed tests with https://travis-ci.org/yceruto/django-ajax/builds/269619322

Are you sure `AJAXMiddleware` is configured like this:
```python
MIDDLEWARE_CLASSES = (
    # ...
    'django_ajax.middleware.AJAXMiddleware',
)
```
Note that when you're using `AJAXMiddleware` you can't use `@ajax` decorator at the same time.

**Comment by yceruto** [comment]
Please, reopen this issue if the problem persists, thanks.
