### ISSUE TITLE
.js files not on the master branch.

### ISSUE THREAD

**Issue by dieterrosch** [yceruto/django-ajax#43]
Hi,

After spending a few hours searching for the static django_ajax/*.js files on the net, I finally found them on the stale gh-pages branch. I suspect they were missed in a site move or restructure.

**Comment by yceruto** [comment]
Thanks for report it. This package does not support the js files anymore, but you can still use it from old version (see related issue).

I'm closing this as duplicated of https://github.com/yceruto/django-ajax/issues/42

**Comment by ajeebkp23** [comment]
It would be nice, if you can update this link as well [http://yceruto.github.io/django-ajax/](http://yceruto.github.io/django-ajax/) Otherwise, people like me have to search in issue tracker and reach here.
