### ISSUE TITLE
Could the main release also be Django 1.11 LTS compatible?

### ISSUE THREAD

**Issue by mbourqui** [yceruto/django-ajax#45]
Django 1.11 is the latest LTS release, it would be nice to support it (at least on PyPI) as long as the 2.X LTS is not available.

**Comment by yceruto** [comment]
Hi @mbourqui, Django 1.11 LTS is supported for `djangoajax==2.*`. And Django 2+ for `djangoajax==3.*`. Try this `pip install djangoajax==2.*` and let me know if all work fine. Cheers!

**Comment by mbourqui** [comment]
Hi @yceruto,
Thanks for your quick reply!
Unfortunately, the 2.4.1 release is already set up for Django 2.X. But otherwise you're right, I could install the 2.4.0 version wiht `pip install djangoajax==2.4.0`.

**Comment by yceruto** [comment]
> Unfortunately, the 2.4.1 release is already set up for Django 2.X.

That's my fault, it's fixed now in [`2.4.5`](https://github.com/yceruto/django-ajax/releases/tag/2.4.5) - [Travis build](https://travis-ci.org/yceruto/django-ajax/builds/358899728)

Thank you.
