### ISSUE TITLE
class based view (CreateView)  with AJAXMixin

### ISSUE THREAD

**Issue by khaldon** [yceruto/django-ajax#52]
the error is **This page isn’t working** and **HTTP ERROR 400** in the terminal show me **Bad request**

**Comment by yceruto** [comment]
Hi @khaldon, I'll take a look at this class, meanwhile could you show me the whole errors trace?

**Comment by yceruto** [comment]
Could you show me how this class definition looks like? For example, this is how I tried it:
https://github.com/yceruto/django-ajax/blob/d5af47c0e65571d4729f48781c0b41886b926221/tests/ajaxdecorator/app/views.py#L26-L29

**Comment by khaldon** [comment]
**this the code** 
![screenshot from 2019-02-18 16-37-10](https://user-images.githubusercontent.com/10290194/52957918-8cff4d80-339b-11e9-9713-dc3a47cde231.png)
**this error** 
![screenshot from 2019-02-18 16-38-28](https://user-images.githubusercontent.com/10290194/52957982-b6b87480-339b-11e9-8329-9e0d4459c1cb.png)

**Comment by yceruto** [comment]
Are you accessing to this URI through a non-AJAX call? 

By default it's mandatory, but you can make it optional by configuring `ajax_mandatory` manually:
```python
class CreatContact(AJAXMixin, CreateView):
    # ...
    ajax_mandatory = False
```

So this is not a bug, but a usage issue, thanks for reporting it, I'll try to update the docs to make it clear.

**Comment by khaldon** [comment]
Thank you , that's work well.  but I want to know how about dealing with Template and recieve or fetch data from model that automatic work or what will happen ?
