### ISSUE TITLE
Not receveing ADMIN error emails

### ISSUE THREAD

**Issue by paolobb4** [yceruto/django-ajax#53]
I can't debug my deployed application because django-ajax is catching all errors and I'm not getting the ADMIN emails :/ 
(I'm now thinking of sending the error back from client side just to report it @_@)

Maybe there's a way to force admin error emails?

**Comment by yceruto** [comment]
Hi @paolobb4 probably I need to disable it on non-debug mode.

**Comment by paolobb4** [comment]
I also keep gettin this message whenever there's an error. I guess there's a problem with the logging settings(?
```No handlers could be found for logger "django_ajax.shortcuts"```

**Comment by paolobb4** [comment]
I've just realized that the error messages that django-ajax catches and passes to the client has server data that probably shouldn't be seen by outsiders...

Maybe it would be best if only the error code be passed to the client and the message be sent to admins through email wich is standard django behavior.
