### ISSUE TITLE
cannot import name 'ajax' from 'django_ajax.decorators' 

### ISSUE THREAD

**Issue by NeilduToit13** [yceruto/django-ajax#62]
I started getting this on my production site today. Development site still worked. I uninstalled and reinstalled the dev package keeping the exact same version and then I got the same error in dev environment as well. Then I bumped the version to latest and now no error. 
Did you perhaps break your previous version when creating your new version?

**Comment by yceruto** [comment]
I will check the previous version, thanks for reporting it!
